entrypoint: python serve_stable_diffusion.py
cluster_env: stable-diffusion-deploy:3
runtime_env:
  working_dir: https://github.com/robertnishihara/test-deploy-stable-diffusion/zipball/main
healthcheck_url: "/healthcheck"
